In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [28]:
type( 5* 5.)

float

In [2]:
sales = pd.read_csv(r"C:\Users\pc\Desktop\Data Science Folder\Retail1\sales data-set.csv")

stores = pd.read_csv(r"C:\Users\pc\Desktop\Data Science Folder\Retail1\sales data-set.csv")

features = pd.read_csv(r"C:\Users\pc\Desktop\Data Science Folder\Retail1\Features data set.csv")

In [3]:

"""
change date format from j/m/a to a-m-j
"""

features['Date'] = pd.to_datetime(features['Date'])
sales['Date'] = pd.to_datetime(sales['Date'])

In [6]:
print(sales[0:1].Date, '\n', sales[-1:].Date)

0   2010-05-02
Name: Date, dtype: datetime64[ns]
 421569   2012-10-26
Name: Date, dtype: datetime64[ns]

In [9]:
print(sales[0:1].Date, '\n',  sales[-1:].Date)

0   2010-05-02
Name: Date, dtype: datetime64[ns]
 421569   2012-10-26
Name: Date, dtype: datetime64[ns]

In [21]:
print("sales", '\n', sales.head() )
print( "feautures", '\n', features.head())
print( "stores", '\n', stores.head() )

sales
    Store  Dept       Date  Weekly_Sales  IsHoliday
0      1     1 2010-05-02      24924.50      False
1      1     1 2010-12-02      46039.49       True
2      1     1 2010-02-19      41595.55      False
3      1     1 2010-02-26      19403.54      False
4      1     1 2010-05-03      21827.90      False
feautures
    Store       Date  Temperature  Fuel_Price  MarkDown1  MarkDown2  MarkDown3  \
0      1 2010-05-02        42.31       2.572        NaN        NaN        NaN
1      1 2010-12-02        38.51       2.548        NaN        NaN        NaN
2      1 2010-02-19        39.93       2.514        NaN        NaN        NaN
3      1 2010-02-26        46.63       2.561        NaN        NaN        NaN
4      1 2010-05-03        46.50       2.625        NaN        NaN        NaN

   MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday
0        NaN        NaN  211.096358         8.106      False
1        NaN        NaN  211.242170         8.106       True
2        NaN        NaN  211.289143         8.106      False
3        NaN        NaN  211.319643         8.106      False
4        NaN        NaN  211.350143         8.106      False
store
    Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  05/02/2010      24924.50      False
1      1     1  12/02/2010      46039.49       True
2      1     1  19/02/2010      41595.55      False
3      1     1  26/02/2010      19403.54      False
4      1     1  05/03/2010      21827.90      False

In [18]:
df=pd.merge(sales,features, on=['Store','Date', 'IsHoliday'], how='left')
df

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,1,1,2010-05-02,24924.50,False,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106
1,1,1,2010-12-02,46039.49,True,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106
2,1,1,2010-02-19,41595.55,False,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106
3,1,1,2010-02-26,19403.54,False,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106
4,1,1,2010-05-03,21827.90,False,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106
5,1,1,2010-12-03,21043.39,False,57.79,2.667,NaN,NaN,NaN,NaN,NaN,211.380643,8.106
6,1,1,2010-03-19,22136.64,False,54.58,2.720,NaN,NaN,NaN,NaN,NaN,211.215635,8.106
7,1,1,2010-03-26,26229.21,False,51.45,2.732,NaN,NaN,NaN,NaN,NaN,211.018042,8.106
8,1,1,2010-02-04,57258.43,False,62.27,2.719,NaN,NaN,NaN,NaN,NaN,210.820450,7.808
9,1,1,2010-09-04,42960.91,False,65.86,2.770,NaN,NaN,NaN,NaN,NaN,210.622857,7.808
10,1,1,2010-04-16,17596.96,False,66.32,2.808,NaN,NaN,NaN,NaN,NaN,210.488700,7.808
11,1,1,2010-04-23,16145.35,False,64.84,2.795,NaN,NaN,NaN,NaN,NaN,210.439123,7.808
12,1,1,2010-04-30,16555.11,False,67.41,2.780,NaN,NaN,NaN,NaN,NaN,210.389546,7.808
13,1,1,2010-07-05,17413.94,False,72.55,2.835,NaN,NaN,NaN,NaN,NaN,210.339968,7.808
14,1,1,2010-05-14,18926.74,False,74.78,2.854,NaN,NaN,NaN,NaN,NaN,210.337426,7.808
15,1,1,2010-05-21,14773.04,False,76.44,2.826,NaN,NaN,NaN,NaN,NaN,210.617093,7.808
16,1,1,2010-05-28,15580.43,False,80.44,2.759,NaN,NaN,NaN,NaN,NaN,210.896761,7.808
17,1,1,2010-04-06,17558.09,False,80.69,2.705,NaN,NaN,NaN,NaN,NaN,211.176428,7.808
18,1,1,2010-11-06,16637.62,False,80.43,2.668,NaN,NaN,NaN,NaN,NaN,211.456095,7.808
19,1,1,2010-06-18,16216.27,False,84.11,2.637,NaN,NaN,NaN,NaN,NaN,211.453772,7.808
20,1,1,2010-06-25,16328.72,False,84.34,2.653,NaN,NaN,NaN,NaN,NaN,211.338653,7.808
21,1,1,2010-02-07,16333.14,False,80.91,2.669,NaN,NaN,NaN,NaN,NaN,211.223533,7.787
22,1,1,2010-09-07,17688.76,False,80.48,2.642,NaN,NaN,NaN,NaN,NaN,211.108414,7.787
23,1,1,2010-07-16,17150.84,False,83.15,2.623,NaN,NaN,NaN,NaN,NaN,211.100385,7.787
24,1,1,2010-07-23,15360.45,False,83.36,2.608,NaN,NaN,NaN,NaN,NaN,211.235144,7.787
25,1,1,2010-07-30,15381.82,False,81.84,2.640,NaN,NaN,NaN,NaN,NaN,211.369903,7.787
26,1,1,2010-06-08,17508.41,False,87.16,2.627,NaN,NaN,NaN,NaN,NaN,211.504662,7.787
27,1,1,2010-08-13,15536.40,False,87.00,2.692,NaN,NaN,NaN,NaN,NaN,211.639421,7.787
28,1,1,2010-08-20,15740.13,False,86.65,2.664,NaN,NaN,NaN,NaN,NaN,211.603363,7.787
29,1,1,2010-08-27,15793.87,False,85.22,2.619,NaN,NaN,NaN,NaN,NaN,211.567306,7.787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421540,45,98,2012-06-04,778.70,False,49.73,3.996,13450.45,NaN,26.59,3363.54,3962.01,190.685171,8.567
421541,45,98,2012-04-13,559.14,False,51.83,4.044,4736.94,6047.12,16.68,1355.11,2246.12,190.759596,8.567
421542,45,98,2012-04-20,605.80,False,63.13,4.027,9210.90,2667.05,6.25,970.33,2568.22,190.813801,8.567
421543,45,98,2012-04-27,619.41,False,53.20,4.004,2872.86,0.03,37.12,74.97,2495.29,190.868006,8.567
421544,45,98,2012-04-05,694.25,False,55.21,3.951,11984.62,NaN,47.52,6150.63,1775.54,190.922212,8.567
421545,45,98,2012-11-05,893.60,False,61.24,3.889,12611.18,NaN,21.36,1667.39,2313.12,190.976417,8.567
421546,45,98,2012-05-18,745.44,False,66.30,3.848,6813.74,NaN,13.86,936.49,2941.55,190.996448,8.567
421547,45,98,2012-05-25,795.94,False,67.21,3.798,5370.39,NaN,361.22,1287.62,2461.81,191.002810,8.567
421548,45,98,2012-01-06,874.64,False,74.48,3.742,10643.62,48.20,201.56,2599.35,1856.97,191.009171,8.567
421549,45,98,2012-08-06,713.50,False,64.30,3.689,8429.61,148.60,76.15,1465.54,7180.97,191.015533,8.567
421550,45,98,2012-06-15,856.35,False,71.93,3.620,8148.19,252.70,90.05,1226.11,2942.39,191.029973,8.567
421551,45,98,2012-06-22,622.62,False,74.22,3.564,5565.31,222.50,1.16,2149.76,7474.76,191.064610,8.567
421552,45,98,2012-06-29,690.52,False,75.22,3.506,3291.36,425.60,NaN,314.88,2255.34,191.099246,8.567
421553,45,98,2012-06-07,659.65,False,82.99,3.475,5878.09,169.00,64.36,2996.47,5477.04,191.133883,8.684
421554,45,98,2012-07-13,695.21,False,79.97,3.523,2978.08,118.90,22.07,1899.54,5181.94,191.168519,8.684
421555,45,98,2012-07-20,845.30,False,78.89,3.567,6682.75,24.24,12.83,2249.85,2288.30,191.167043,8.684
421556,45,98,2012-07-27,657.63,False,77.20,3.647,5753.81,167.95,1.23,9181.48,3156.06,191.165566,8.684
421557,45,98,2012-03-08,516.46,False,76.58,3.654,24853.05,39.56,17.96,11142.69,2768.32,191.164090,8.684
421558,45,98,2012-10-08,727.49,False,78.65,3.722,17868.84,50.60,57.66,2593.93,1890.59,191.162613,8.684
421559,45,98,2012-08-17,500.16,False,75.71,3.807,3657.79,6.00,0.30,1630.50,3794.22,191.228492,8.684
421560,45,98,2012-08-24,415.40,False,72.62,3.834,7936.20,58.38,22.00,5518.07,2291.97,191.344887,8.684
421561,45,98,2012-08-31,346.04,False,75.09,3.867,23641.30,6.00,92.93,6988.31,3992.13,191.461281,8.684
421562,45,98,2012-07-09,352.44,True,75.70,3.911,11024.45,12.80,52.63,1854.77,2055.70,191.577676,8.684
421563,45,98,2012-09-14,605.96,False,67.87,3.948,11407.95,NaN,4.30,3421.72,5268.92,191.699850,8.684
421564,45,98,2012-09-21,467.30,False,65.32,4.038,8452.20,92.28,63.24,2376.38,8670.40,191.856704,8.684
421565,45,98,2012-09-28,508.37,False,64.88,3.997,4556.61,20.64,1.50,1601.01,3288.25,192.013558,8.684
421566,45,98,2012-05-10,628.10,False,64.89,3.985,5046.74,NaN,18.82,2253.43,2340.01,192.170412,8.667
421567,45,98,2012-12-10,1061.02,False,54.47,4.000,1956.28,NaN,7.89,599.32,3990.54,192.327265,8.667
421568,45,98,2012-10-19,760.01,False,56.47,3.969,2004.02,NaN,3.18,437.73,1537.49,192.330854,8.667
421569,45,98,2012-10-26,1076.80,False,58.85,3.882,4018.91,58.08,100.00,211.94,858.33,192.308899,8.667

In [25]:
df =  pd.merge(df,stores, on=['Store'], how='left')
print( df )

MemoryError:

In [23]:
df

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,1,1,2010-05-02,24924.50,False,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106
1,1,1,2010-12-02,46039.49,True,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106
2,1,1,2010-02-19,41595.55,False,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106
3,1,1,2010-02-26,19403.54,False,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106
4,1,1,2010-05-03,21827.90,False,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106
5,1,1,2010-12-03,21043.39,False,57.79,2.667,NaN,NaN,NaN,NaN,NaN,211.380643,8.106
6,1,1,2010-03-19,22136.64,False,54.58,2.720,NaN,NaN,NaN,NaN,NaN,211.215635,8.106
7,1,1,2010-03-26,26229.21,False,51.45,2.732,NaN,NaN,NaN,NaN,NaN,211.018042,8.106
8,1,1,2010-02-04,57258.43,False,62.27,2.719,NaN,NaN,NaN,NaN,NaN,210.820450,7.808
9,1,1,2010-09-04,42960.91,False,65.86,2.770,NaN,NaN,NaN,NaN,NaN,210.622857,7.808
10,1,1,2010-04-16,17596.96,False,66.32,2.808,NaN,NaN,NaN,NaN,NaN,210.488700,7.808
11,1,1,2010-04-23,16145.35,False,64.84,2.795,NaN,NaN,NaN,NaN,NaN,210.439123,7.808
12,1,1,2010-04-30,16555.11,False,67.41,2.780,NaN,NaN,NaN,NaN,NaN,210.389546,7.808
13,1,1,2010-07-05,17413.94,False,72.55,2.835,NaN,NaN,NaN,NaN,NaN,210.339968,7.808
14,1,1,2010-05-14,18926.74,False,74.78,2.854,NaN,NaN,NaN,NaN,NaN,210.337426,7.808
15,1,1,2010-05-21,14773.04,False,76.44,2.826,NaN,NaN,NaN,NaN,NaN,210.617093,7.808
16,1,1,2010-05-28,15580.43,False,80.44,2.759,NaN,NaN,NaN,NaN,NaN,210.896761,7.808
17,1,1,2010-04-06,17558.09,False,80.69,2.705,NaN,NaN,NaN,NaN,NaN,211.176428,7.808
18,1,1,2010-11-06,16637.62,False,80.43,2.668,NaN,NaN,NaN,NaN,NaN,211.456095,7.808
19,1,1,2010-06-18,16216.27,False,84.11,2.637,NaN,NaN,NaN,NaN,NaN,211.453772,7.808
20,1,1,2010-06-25,16328.72,False,84.34,2.653,NaN,NaN,NaN,NaN,NaN,211.338653,7.808
21,1,1,2010-02-07,16333.14,False,80.91,2.669,NaN,NaN,NaN,NaN,NaN,211.223533,7.787
22,1,1,2010-09-07,17688.76,False,80.48,2.642,NaN,NaN,NaN,NaN,NaN,211.108414,7.787
23,1,1,2010-07-16,17150.84,False,83.15,2.623,NaN,NaN,NaN,NaN,NaN,211.100385,7.787
24,1,1,2010-07-23,15360.45,False,83.36,2.608,NaN,NaN,NaN,NaN,NaN,211.235144,7.787
25,1,1,2010-07-30,15381.82,False,81.84,2.640,NaN,NaN,NaN,NaN,NaN,211.369903,7.787
26,1,1,2010-06-08,17508.41,False,87.16,2.627,NaN,NaN,NaN,NaN,NaN,211.504662,7.787
27,1,1,2010-08-13,15536.40,False,87.00,2.692,NaN,NaN,NaN,NaN,NaN,211.639421,7.787
28,1,1,2010-08-20,15740.13,False,86.65,2.664,NaN,NaN,NaN,NaN,NaN,211.603363,7.787
29,1,1,2010-08-27,15793.87,False,85.22,2.619,NaN,NaN,NaN,NaN,NaN,211.567306,7.787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421540,45,98,2012-06-04,778.70,False,49.73,3.996,13450.45,NaN,26.59,3363.54,3962.01,190.685171,8.567
421541,45,98,2012-04-13,559.14,False,51.83,4.044,4736.94,6047.12,16.68,1355.11,2246.12,190.759596,8.567
421542,45,98,2012-04-20,605.80,False,63.13,4.027,9210.90,2667.05,6.25,970.33,2568.22,190.813801,8.567
421543,45,98,2012-04-27,619.41,False,53.20,4.004,2872.86,0.03,37.12,74.97,2495.29,190.868006,8.567
421544,45,98,2012-04-05,694.25,False,55.21,3.951,11984.62,NaN,47.52,6150.63,1775.54,190.922212,8.567
421545,45,98,2012-11-05,893.60,False,61.24,3.889,12611.18,NaN,21.36,1667.39,2313.12,190.976417,8.567
421546,45,98,2012-05-18,745.44,False,66.30,3.848,6813.74,NaN,13.86,936.49,2941.55,190.996448,8.567
421547,45,98,2012-05-25,795.94,False,67.21,3.798,5370.39,NaN,361.22,1287.62,2461.81,191.002810,8.567
421548,45,98,2012-01-06,874.64,False,74.48,3.742,10643.62,48.20,201.56,2599.35,1856.97,191.009171,8.567
421549,45,98,2012-08-06,713.50,False,64.30,3.689,8429.61,148.60,76.15,1465.54,7180.97,191.015533,8.567
421550,45,98,2012-06-15,856.35,False,71.93,3.620,8148.19,252.70,90.05,1226.11,2942.39,191.029973,8.567
421551,45,98,2012-06-22,622.62,False,74.22,3.564,5565.31,222.50,1.16,2149.76,7474.76,191.064610,8.567
421552,45,98,2012-06-29,690.52,False,75.22,3.506,3291.36,425.60,NaN,314.88,2255.34,191.099246,8.567
421553,45,98,2012-06-07,659.65,False,82.99,3.475,5878.09,169.00,64.36,2996.47,5477.04,191.133883,8.684
421554,45,98,2012-07-13,695.21,False,79.97,3.523,2978.08,118.90,22.07,1899.54,5181.94,191.168519,8.684
421555,45,98,2012-07-20,845.30,False,78.89,3.567,6682.75,24.24,12.83,2249.85,2288.30,191.167043,8.684
421556,45,98,2012-07-27,657.63,False,77.20,3.647,5753.81,167.95,1.23,9181.48,3156.06,191.165566,8.684
421557,45,98,2012-03-08,516.46,False,76.58,3.654,24853.05,39.56,17.96,11142.69,2768.32,191.164090,8.684
421558,45,98,2012-10-08,727.49,False,78.65,3.722,17868.84,50.60,57.66,2593.93,1890.59,191.162613,8.684
421559,45,98,2012-08-17,500.16,False,75.71,3.807,3657.79,6.00,0.30,1630.50,3794.22,191.228492,8.684
421560,45,98,2012-08-24,415.40,False,72.62,3.834,7936.20,58.38,22.00,5518.07,2291.97,191.344887,8.684
421561,45,98,2012-08-31,346.04,False,75.09,3.867,23641.30,6.00,92.93,6988.31,3992.13,191.461281,8.684
421562,45,98,2012-07-09,352.44,True,75.70,3.911,11024.45,12.80,52.63,1854.77,2055.70,191.577676,8.684
421563,45,98,2012-09-14,605.96,False,67.87,3.948,11407.95,NaN,4.30,3421.72,5268.92,191.699850,8.684
421564,45,98,2012-09-21,467.30,False,65.32,4.038,8452.20,92.28,63.24,2376.38,8670.40,191.856704,8.684
421565,45,98,2012-09-28,508.37,False,64.88,3.997,4556.61,20.64,1.50,1601.01,3288.25,192.013558,8.684
421566,45,98,2012-05-10,628.10,False,64.89,3.985,5046.74,NaN,18.82,2253.43,2340.01,192.170412,8.667
421567,45,98,2012-12-10,1061.02,False,54.47,4.000,1956.28,NaN,7.89,599.32,3990.54,192.327265,8.667
421568,45,98,2012-10-19,760.01,False,56.47,3.969,2004.02,NaN,3.18,437.73,1537.49,192.330854,8.667
421569,45,98,2012-10-26,1076.80,False,58.85,3.882,4018.91,58.08,100.00,211.94,858.33,192.308899,8.667